[package]
name = "hw3"
version = "0.1.0"
authors = ["nalane <nathaniel.patrick.lane@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-lzma = "0.5.1"
clap = "2.33"